import {CONFIG,createGame,applyAction,applyOffline,getLegalActions,summarize} from "./game.js";
import {loadProgress,saveProgress} from "./persist.js"; import {GameAudio} from "./audio.js";
const $=q=>document.querySelector(q), audio=new GameAudio(); let state=createGame({seed:new Date().getDate()}),saved={};
function stats(f){const id=CONFIG.id;if(id==="pg-township")return Object.entries(f.affection).map(([k,v])=>k+" "+v).join(" · ")+" · Day "+f.day;if(id==="pg-campusbond")return Object.entries(f.stats).map(([k,v])=>k+" "+v).join(" · ");if(id==="pg-ghostmark")return "Mission "+f.mission+" · Alert "+f.alert+"% · "+(f.target?"TARGET SECURED":"SEARCHING");if(id==="pg-blackward")return "🔋"+f.battery+" · noise "+f.noise+" · keys "+f.keys+"/3";if(id==="pg-blockcity")return "人口 "+f.pop+" · 幸福 "+f.happy+" · 污染 "+f.pollution;if(id==="pg-porttycoon")return "Q"+f.quarter+" · 市值 "+f.value+" / Rival "+f.rival;if(id==="pg-templeidle")return "香火 "+Math.floor(f.incense)+" · 香爐 "+f.generators+" · 金身 "+f.prestige;return "SCORE "+state.score+" · 資源 "+state.resources}
function scene(f){const id=CONFIG.id;if(id==="pg-casefile")return '<div class="room"><b>'+f.rooms[f.room]+'</b><i class="hotspot"></i><span>'+f.clues.join(" / ")+'</span></div>';if(id==="pg-township")return '<div class="portrait">◐</div><blockquote>'+state.msg+'</blockquote>';if(id==="pg-campusbond")return '<div class="week">'+f.schedule.map((x,i)=>'<i title="'+x+'">'+(i+1)+'</i>').join("")+'</div>';if(id==="pg-blockcity")return '<div class="grid">'+f.grid.map(x=>'<i class="'+x+'"></i>').join("")+'</div>';if(id==="pg-porttycoon")return '<div class="chart">'+f.history.map((x,i)=>'<i style="height:'+x[0]*2+'px;left:'+i*12+'px"></i><b style="height:'+x[1]*2+'px;left:'+(i*12+5)+'px"></b>').join("")+'</div>';if(id==="pg-empirekitchen")return '<div class="orders">'+Array.from({length:f.orders},(_,i)=>'<i style="--n:'+i+'">單 '+(i+1)+'</i>').join("")+'</div>';if(id==="pg-seacast")return '<div class="sea"><span class="fish">𓆝</span><i style="height:'+f.tension+'%"></i><b>'+f.weather+' · '+["防波堤","紅樹林","外海礁"][f.spot]+'</b></div>';if(id==="pg-templeidle")return '<div class="temple"><span>卍</span><i>'+("✦".repeat(Math.min(16,f.generators*f.multiplier)))+'</i></div>';if(id==="pg-backdoor")return '<div class="map">'+Object.entries(f.skills).map(([k,v])=>'<i class="'+k+'">'+k.toUpperCase()+' '+v+'/4</i>').join("")+'</div>';return '<canvas id="field" width="640" height="260"></canvas>'}
function canvas(f){const c=$("#field");if(!c)return;const x=c.getContext("2d");x.fillStyle=CONFIG.id==="pg-blackward"?"#08090a":"#0c1820";x.fillRect(0,0,640,260);x.strokeStyle="#263842";for(let i=0;i<10;i++)x.strokeRect(i*70,30+(i%2)*70,55,45);if(CONFIG.id==="pg-ghostmark"){x.fillStyle="#83f28f33";x.beginPath();x.moveTo(420,100);x.lineTo(220,20);x.lineTo(220,180);x.fill();x.fillStyle="#83f28f";x.fillRect(Math.min(570,f.distance*5),195,16,16);x.fillStyle="#ff5f5f";x.fillRect(420,90,14,22)}else{const g=x.createRadialGradient(180+f.distance*3,130,10,180+f.distance*3,130,Math.max(35,f.battery*2));g.addColorStop(0,"#fffbd0");g.addColorStop(1,"#000");x.fillStyle=g;x.globalCompositeOperation="screen";x.fillRect(0,0,640,260);x.globalCompositeOperation="source-over";x.fillStyle="#551b1b";x.fillRect(570-f.threat*3,80,10,80)}}
function render(){const v=summarize(state);$("#stats").textContent=stats(v.flags);$("#message").textContent=v.msg;$("#scene").innerHTML=scene(v.flags);canvas(v.flags);const a=$("#actions");a.innerHTML="";for(const key of getLegalActions(state)){const b=document.createElement("button");b.textContent=CONFIG.actions[key];b.onclick=()=>{audio.fx(key==="commit"?"win":"tap");state=applyAction(state,key);void save();render()};a.append(b)}if(state.outcome!=="playing"){const b=document.createElement("button");b.className="restart";b.textContent="重新開始";b.onclick=()=>{state=createGame({seed:Date.now()%99});render()};a.append(b)}}
async function save(){saved={state,best:Math.max(saved.best||0,state.score)};await saveProgress(saved)}
async function boot(){document.title=CONFIG.title;$("#title").textContent=CONFIG.title;$("#genre").textContent=CONFIG.genre;$("#help").textContent=CONFIG.help;saved=await loadProgress();if(saved.state&&CONFIG.id==="pg-templeidle")state=applyOffline(saved.state);$("#sound").onclick=()=>audio.toggle($("#sound"));$("#start").onclick=async()=>{await audio.start();$("#intro").hidden=true;$("#game").hidden=false;render()};render()}boot();
